import {
  createWorktree,
  writeWorktreeFile,
  commitAll,
  pushBranch,
  removeWorktree,
  getDefaultBranch,
} from "../tools/localRepo";
import {
  createPullRequest,
  getExistingPullRequest,
  postIssueComment,
  getGithubToken,
} from "../tools/githubWrite";
import { rememberFix } from "../memory/agentMemory";
import { log, type PipelineStateType } from "../graph/state";

/**
 * Terminal node for the decline path. Posts the Planner's comment and stops.
 * No branch, no worktree, no pull request.
 */
export async function declineNode(state: PipelineStateType) {
  const body = `${state.declineComment}

<sub>Automated triage by DevMind. Reopen or add detail and I'll take another look.</sub>`;

  await postIssueComment(state.owner, state.repoName, state.issueNumber, body);

  return log("system", `declined issue #${state.issueNumber} and commented`);
}

/**
 * Terminal node for the fix path: materialise the diff, push, open the PR.
 *
 * The worktree is created here rather than up front so the review loop never
 * touches the filesystem — only an accepted change gets written anywhere.
 */
export async function finalizeNode(state: PipelineStateType) {
  if (state.codeDiffs.length === 0) {
    const body = `DevMind analysed this issue but could not produce a working change.

**Plan attempted:** ${state.plan || "(none)"}
**Last review feedback:** ${state.reviewFeedback || "(none)"}

<sub>Automated by DevMind.</sub>`;
    await postIssueComment(state.owner, state.repoName, state.issueNumber, body);
    return log("system", "no diffs to apply — commented instead of opening a PR");
  }

  const branch = state.branch || `devmind/issue-${state.issueNumber}`;
  const wt = await createWorktree(state.clonePath, branch);

  try {
    for (const d of state.codeDiffs) {
      await writeWorktreeFile(wt, d.file_path, d.patched);
    }

    const committed = await commitAll(
      wt,
      `fix: ${state.issueTitle}\n\nCloses #${state.issueNumber}\n\n${state.codeSummary}`
    );
    if (!committed) {
      return log("system", "working tree clean after writes — nothing to push");
    }

    await pushBranch(wt, state.owner, state.repoName, getGithubToken());

    const base = await getDefaultBranch(state.clonePath);
    const passedReview = state.reviewScore >= 7;

    const prBody = `Closes #${state.issueNumber}

## What changed
${state.codeSummary}

## Plan
${state.plan}

## Automated review
**Score: ${state.reviewScore}/10** after ${state.iterationCount} iteration(s)${
      passedReview
        ? ""
        : "\n\n> This did not reach the passing score of 7. It is opened for human judgement rather than discarded — review carefully."
    }
${state.reviewFeedback ? `\n${state.reviewFeedback}` : ""}

## Files
${state.codeDiffs.map((d) => `- \`${d.file_path}\``).join("\n")}

<sub>Generated by DevMind. Nothing merges without your approval.</sub>`;

    const existingPr = await getExistingPullRequest(state.owner, state.repoName, branch);
    let prUrl = existingPr;

    if (!prUrl) {
      prUrl = await createPullRequest({
        owner: state.owner,
        repo: state.repoName,
        head: branch,
        base,
        title: `fix: ${state.issueTitle}`,
        body: prBody,
      });

      await postIssueComment(
        state.owner,
        state.repoName,
        state.issueNumber,
        `Opened a pull request with a proposed fix: ${prUrl}\n\n<sub>Automated by DevMind.</sub>`
      );
    } else {
      await postIssueComment(
        state.owner,
        state.repoName,
        state.issueNumber,
        `Pushed updated revisions to existing pull request: ${prUrl}\n\n**What changed:**\n${state.codeSummary}\n\n<sub>Automated by DevMind.</sub>`
      );
    }

    await rememberFix(
      state.repoId,
      `Issue #${state.issueNumber} "${state.issueTitle}" — ${state.codeSummary} (files: ${state.codeDiffs
        .map((d) => d.file_path)
        .join(", ")})`
    );

    return { prUrl, ...log("system", `opened PR ${prUrl}`) };
  } finally {
    // Always clean up, including on push/PR failure — a stale worktree blocks
    // the branch name on the next run.
    await removeWorktree(state.clonePath, wt);
  }
}
