import { Router, type Request, type Response } from "express";
import { createHmac, timingSafeEqual } from "node:crypto";
import { sql } from "../db/client";
import { enqueueFixIssue } from "../services/queue";
import { getPullRequest } from "../services/github";
import type { Job, Repo } from "@devmind/shared";

const GITHUB_WEBHOOK_SECRET = process.env.GITHUB_WEBHOOK_SECRET ?? "";

const router = Router();

// ─── POST /api/webhook/:repo_id ───────────────────────────────────────────────
// NOTE: this router MUST be mounted with express.raw() (see index.ts) so the
// HMAC can be computed over the exact bytes GitHub signed. Once JSON is parsed
// and re-serialized, whitespace/ordering changes invalidate the signature.

router.post("/:repo_id", async (req: Request, res: Response) => {
  const rawBody = req.body as Buffer;
  if (!Buffer.isBuffer(rawBody)) {
    return res.status(400).json({ error: "expected_raw_body" });
  }

  // ── 1. Verify signature (constant-time) ─────────────────────────────────────
  const signatureHeader = req.header("x-hub-signature-256") ?? "";
  const expected =
    "sha256=" +
    createHmac("sha256", GITHUB_WEBHOOK_SECRET).update(rawBody).digest("hex");

  const a = Buffer.from(signatureHeader);
  const b = Buffer.from(expected);
  if (a.length !== b.length || !timingSafeEqual(a, b)) {
    return res.status(401).json({ error: "invalid_signature" });
  }

  // ── 2. Parse payload + event ────────────────────────────────────────────────
  let payload: any;
  try {
    payload = JSON.parse(rawBody.toString("utf8"));
  } catch {
    return res.status(400).json({ error: "invalid_json" });
  }
  const event = req.header("x-github-event");

  // Ping is sent by GitHub when a webhook is first created. Just ack it.
  if (event === "ping") {
    return res.status(200).json({ pong: true });
  }

  const isIssueOpened = event === "issues" && payload?.action === "opened";
  const isCommentCreated =
    (event === "issue_comment" || event === "pull_request_review_comment") &&
    payload?.action === "created";
  const isReviewSubmitted =
    event === "pull_request_review" && payload?.action === "submitted";

  // Only issue-opened, comment-created, or review-submitted events produce work.
  // Everything else is acknowledged with 204 so GitHub does not retry.
  if (!isIssueOpened && !isCommentCreated && !isReviewSubmitted) {
    return res.status(204).end();
  }

  // ── Handle Comment / Review Mention Check ─────────────────────────────────
  let commentFeedback: string | undefined = undefined;

  if (isCommentCreated || isReviewSubmitted) {
    const comment = payload.comment ?? payload.review;
    const author = String(comment?.user?.login ?? "");
    const commentBody = String(comment?.body ?? "");

    if (!commentBody.trim()) {
      return res.status(204).end();
    }

    // Ignore bot comments and DevMind's own automated comments
    const isDevMindWatermark =
      commentBody.includes("Automated by DevMind") ||
      commentBody.includes("Automated triage by DevMind") ||
      commentBody.includes("Generated by DevMind");

    const isBot =
      comment?.user?.type === "Bot" ||
      author.toLowerCase().includes("[bot]") ||
      isDevMindWatermark;

    // Guard against responding to automated comments (prevents infinite loops)
    if (isBot) {
      console.log(`[webhook] Skipping automated/bot comment from ${author}`);
      return res.status(204).end();
    }

    // Mention-only mode: requires @devmind or /devmind
    const isMentioned = /@devmind|\/devmind/i.test(commentBody);
    if (!isMentioned) {
      console.log(`[webhook] Comment from ${author} did not mention @devmind or /devmind. Ignoring.`);
      return res.status(204).end();
    }

    console.log(`[webhook] Processing mention from ${author}: "${commentBody.slice(0, 100)}"`);

    commentFeedback = commentBody;
    if (event === "pull_request_review_comment" && comment?.path) {
      commentFeedback = `Inline review comment on file \`${comment.path}\`:\n\`\`\`diff\n${comment.diff_hunk ?? ""}\n\`\`\`\n\nComment by @${author}:\n${commentBody}`;
    } else if (event === "pull_request_review") {
      commentFeedback = `Pull request review by @${author}:\n${commentBody}`;
    }
  }

  // ── 3. Confirm the repo exists in our DB ────────────────────────────────────
  const repoId = req.params.repo_id;
  const [repo] = await sql<Repo[]>`SELECT * FROM repos WHERE id = ${repoId}`;
  if (!repo) {
    // Signature was valid but we don't know this repo. Return 410 so GitHub
    // eventually disables the delivery attempts.
    return res.status(410).json({ error: "unknown_repo" });
  }

  const issue = payload.issue ?? payload.pull_request;
  if (!issue || typeof issue.number !== "number") {
    return res.status(400).json({ error: "malformed_issue_payload" });
  }

  // ── Determine Target Branch if commenting on a PR ──────────────────────────
  let targetBranch: string | undefined = undefined;
  if (payload.pull_request?.head?.ref) {
    targetBranch = payload.pull_request.head.ref;
  } else if (payload.issue?.pull_request) {
    try {
      const pr = await getPullRequest(repo.owner, repo.repo_name, issue.number);
      targetBranch = pr.head?.ref;
    } catch (err: any) {
      console.warn(`[webhook] Could not resolve PR #${issue.number} branch:`, err.message);
    }
  }

  const baseTitle = String(issue.title ?? "Untitled");
  const jobTitle = commentFeedback ? `[Revision] #${issue.number} ${baseTitle}` : baseTitle;
  const jobBody = commentFeedback
    ? `${issue.body ?? ""}\n\n---\n**Feedback from comment:**\n${commentFeedback}`
    : (issue.body ?? "");

  // ── 4. Insert the job row + enqueue ─────────────────────────────────────────
  try {
    const [job] = await sql<Job[]>`
      INSERT INTO jobs (repo_id, issue_number, issue_title, issue_body)
      VALUES (${repoId}, ${issue.number}, ${jobTitle}, ${jobBody})
      RETURNING *
    `;

    await enqueueFixIssue({
      jobId: job.id,
      repoId,
      owner: repo.owner,
      repoName: repo.repo_name,
      issueNumber: issue.number,
      issueTitle: baseTitle,
      issueBody: issue.body ?? "",
      clonePath: repo.clone_path,
      commentFeedback,
      branch: targetBranch,
    });

    console.log(
      `[webhook] Enqueued job ${job.id} for #${issue.number} (${jobTitle}) branch: ${targetBranch ?? "default"}`
    );

    return res.status(202).json({ jobId: job.id });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[webhook] failed to enqueue fix-issue:", message);
    // 500 makes GitHub retry, which is what we want if enqueue transiently failed.
    return res.status(500).json({ error: "enqueue_failed" });
  }
});

export default router;
